version: '3.7'

services:
  g2i-quiz:
    build: .
    container_name: g2i-quiz
    environment:
      - SKIP_PREFLIGHT_CHECK=true
      - CHOKIDAR_USEPOLLING=true
    working_dir: /app
    stdin_open: true
    command: >
      sh -c "npx npm install && npx npm start"
    ports:
      - '3001:3000'
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./node_modules:/app/node_modules
      - ./public:/app/public
      - ./.eslintrc:/app/.eslintrc
      - ./.eslintignore:/app/.eslintignore
      - ./.babelrc:/app/.babelrc
      - ./jsconfig.json:/app/jsconfig.json
      - ./.prettierrc:/app/.prettierrc
